module.exports = {
    CHANGE_STATUS_SUCCESS: 'Change statu is successfull',
    CHANGE_SPECIAL_SUCCESS: 'Special update was successful',
    CHANGE_STATUS_MULTI_SUCCESS: 'Has %d elements updated successfully',
    CHANGE_GROUP_ACP_SUCCESS: 'Successfully updated Group ACP',
    CHANGE_ORDERING_SUCCESS: 'Updated ordering successful',
    DELETE_SUCCESS: 'Deleted element successfully',
    DELETE_MULTI_SUCCESS: '%d elements were deleted successfully',
    ADD_SUCCESS: 'Add new element successfully',
    EDIT_SUCCESS: 'Element information updated successfully',
    ERROR_NAME: 'Length from %d to %d characters',
    ERROR_ORDERING: 'Must be an integer greater than%d and less than%d',
    ERROR_STATUS: 'Must be a non-empty value',
    ERROR_SPECIAL: 'Must be a non-null value',
    ERROR_GROUP: 'Must be a non-empty value',
    ERROR_GROUPACP: 'Must be a non-null value',
    ERROR_FILE_REQUIRE: 'Please select upload file',
    ERROR_FILE_LIMIT: 'The file size doesn\'t match',
    ERROR_FILE_EXTENSION: 'Invalid file extension',
    ERROR_LOGIN_USERNAME_NOTEXIST: 'Username does not exist',
    ERROR_LOGIN_PASSWORD_INCORRECT: 'Incorrect password',
    ERROR_LOGIN: 'Incorrect login information',
    FIELD_IS_NOT_EMPTY: 'This field is not empty!',
};
